<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <Import Project="..\netfx.props" />
  <PropertyGroup>
    <Version>2.0.0</Version>
    <AssemblyName>Oxide.MySql</AssemblyName>
    <Authors>Oxide Team and Contributors</Authors>
    <Copyright>(c) 2013-$([System.DateTime]::Now.Year) $(Authors)</Copyright>
    <Description>MySQL database support for the Oxide modding framework</Description>
    <RepositoryUrl>https://github.com/OxideMod/Oxide.MySQL</RepositoryUrl>
    <PackageIconUrl>icon.png</PackageIconUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <TargetFrameworks>net48;netstandard2.0;netstandard2.1</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <NoWarn>NU1701;NU5128</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Oxide.Core" Version="2.0.*" />
    <None Include="..\resources\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.3.7" PrivateAssets="all" />
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.18.1" PrivateAssets="all" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <Import Project="..\OxideILRepack.targets" Condition="Exists('..\OxideILRepack.targets')" />
  <Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Oxide.References'">
        <Aliases>References</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
</Project>
